isommelier/isommelier/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('winereviews/', include('winereviews.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
]

isommelier/polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

isommelier/winereviews/urls.py
from django.urls import path
from django.urls import re_path
from django.conf.urls import url, include
from winereviews.views import ReviewList, ReviewUpdate, ReviewDelete
from winereviews.views import WineList, WineCreate, WineUpdate, WineDelete
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('consultancy/', views.consultancy, name='consultancy'),
    path('worldmap-template/', views.winebycountry, name='worldmap-template'),
    path('wine_variety_stats/', views.wine_variety_stats, name='wine_variety_stats'),
    path('wine_country_report/<countryName>/', views.wine_country_report, name='wine_country_report'),
    path('variety_options/', views.variety_options, name='variety_options'),
    path('variety_reviews/<int:variety_id>', views.variety_reviews, name='variety_reviews'),
    path('wine_review_search/', views.wine_review_search, name='wine_review_search'),
    path('wine_data_viz/', views.wine_data_viz, name='wine_data_viz'),
    path('word_count_stats/<int:number>', views.word_count_stats, name='word_count_stats'),
    path('word_count_stats_expensive/<int:number>', views.word_count_stats_expensive, name='word_count_stats_expensive'),
    path('word_count_stats_rating_hi/<int:number>', views.word_count_stats_rating_hi, name='word_count_stats_rating_hi'),
    path('word_count_stats_rating_lo/<int:number>', views.word_count_stats_rating_lo, name='word_count_stats_rating_lo'),
    
    # Reviews CRUD
    path('review_create/', views.review_create, name='review_create'),
    path('review_delete/<int:review_id>', views.review_delete, name='review_delete'),
    path('review_like/<int:review_id>', views.review_like, name='review_like'),

    path('reviews/', ReviewList.as_view(), name ='reviews'),
    path('review/<int:pk>/', views.review_update, name='review_update'),
    path('review/<int:pk>/delete/', views.review_delete_actual, name='review_delete_actual'),
    path('review/<int:pk>/detail', views.review_detail, name='review_detail'),

    # Wines CRUD
    path('wines/', WineList.as_view(), name='wine_list'),
    path('wine/add/', WineCreate.as_view(), name='wine_add'),
    path('wine/<int:pk>/', WineUpdate.as_view(), name='wine_update'),
    path('wine/<int:pk>/delete/', WineDelete.as_view(), name='wine_delete'),
    path('wine/<int:pk>/detail', views.wine_detail, name='wine_detail'),
    path('wine/<int:pk>/review/', views.wine_review_create, name='wine_review_create'),

    path('wine_type_ahead/', views.wine_type_ahead, name='wine_type_ahead'),

    # path('type_ahead/<str:model>/<str:search>/', views.type_ahead, name='type_ahead'),
    # path('type_ahead/<str:model>/<str:search>/<str:show>/', views.type_ahead, name='type_ahead'),
]

isommelier/winereviews/models.py
from django.conf import settings
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse

# Create your models here.

class Variety(models.Model):
    class Meta:
        verbose_name_plural = "varieties"
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return '%s' % (self.name)

class Winery(models.Model):
    class Meta:
        verbose_name_plural = "wineries"
    name = models.CharField(max_length=255)
    region = models.CharField(max_length=255)
    province = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return '%s' % (self.name)
    
class Wine(models.Model):
    name = models.CharField(max_length=255)
    varietal = models.CharField(max_length=255)
    variety = models.ForeignKey(Variety, on_delete=models.CASCADE)
    winery = models.ForeignKey(Winery, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    vintage = models.IntegerField()

    def __str__(self):
        return '%s' % (self.description)
    def get_absolute_url(self):
        return reverse('wine_detail', kwargs={'pk': self.pk})


class Review(models.Model):
    rating = models.PositiveSmallIntegerField(
        validators=[
            MaxValueValidator(100),
            MinValueValidator(0)
        ],
        blank=True,
        null=True
    )
    comment = models.TextField()
    wine = models.ForeignKey(Wine, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    likes = models.IntegerField()
    flag = models.IntegerField()

    def get_absolute_url(self):
        return reverse('review_detail', kwargs={'pk': self.pk})

    class Winery_report(models.Model):
        name = models.TextField()
        province = models.TextField()
        region = models.TextField()
        country = models.TextField()
        wine_Count = models.IntegerField()
        variety_count = models.IntegerField()

        class Meta:
            managed = False
            db_table = 'winery_report'  # your view name

isommelier/winereviews/forms.py
from django import forms
from .models import Wine, Review
from django.contrib.auth.models import User
from django.db import connection


class WineReviewCreateForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea)
    rating  = forms.IntegerField(min_value=0, max_value=100)
    wine_id = forms.IntegerField(widget=forms.HiddenInput())
    user_id = forms.IntegerField(widget=forms.HiddenInput())

    def save_review(self):
        with connection.cursor() as cursor:
            sql = '''
            INSERT INTO winereviews_review 
            (rating, comment, wine_id, user_id)
            VALUES (%s, %s, %s, %s)
            '''
            cursor.execute(sql, [self.rating, self.comment, self.wine_id, self.user_id])
        pass
    
class WineReviewSearchForm(forms.Form):
    search_query = forms.CharField(label='Search')

class WineReviewHiddenSearchForm(forms.Form):
    search_query = forms.CharField(widget=forms.HiddenInput())

isommelier/winereviews/views.py

import csv
import json
import metapy

from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.views.generic import ListView
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db import connection
from .models import Variety, Review, Wine
from .forms import WineReviewCreateForm, WineReviewSearchForm, WineReviewHiddenSearchForm


def index(request):
    template = loader.get_template('winereviews/index.html')
    context = {
        'a_var': 0,
    }
    return HttpResponse(template.render(context, request))



def winebycountry(request):
    form = WineReviewHiddenSearchForm()
    return render(request, 'winereviews/worldmap-template.html', {'form': form})



def wine_data_viz(request):
    template = loader.get_template('winereviews/wine_data_viz.html')
    context = {
        'form': WineReviewHiddenSearchForm()
    }
    return HttpResponse(template.render(context, request))

    
def word_count_stats_rating_hi(request, number=200):
    response = HttpResponse(content_type='text/plain')

    sql = '''
    SELECT B.word, COUNT(winereviews_review_id) word_count, C.avg_rating
    FROM word_root_review A
    JOIN 
    (
        SELECT Y.root, Y.word 
        FROM (
            SELECT root, MAX(count) AS max_count FROM word_root GROUP BY root
        ) X 
        INNER JOIN word_root Y ON Y.root = X.root 
        AND Y.count = X.max_count GROUP BY Y.root
    ) B ON B.root = A.root
    JOIN word_root_sum C ON C.root = A.root
    WHERE winereviews_review_id IN
        (
            SELECT B.id
            FROM winereviews_review B
            JOIN 
            (
                SELECT A.id, AVG(rating) avg_rating
                FROM winereviews_wine A 
                JOIN winereviews_review B ON B.wine_id = A.id 
                GROUP BY A.id
                ORDER BY avg_rating DESC LIMIT 100
            ) A ON B.wine_id = A.id
        )
    AND A.root NOT IN ('–','—','“','”','$','it','%%','(',')','10')
    AND A.root NOT LIKE '20%%'
    GROUP BY A.root
    ORDER BY word_count DESC, word DESC
    LIMIT %s;
    '''

    # sql = '''
    # SELECT B.word, COUNT(winereviews_review_id) word_count, AVG(C.rating) avg_rating
    # FROM word_root_review A
    # JOIN 
    # (
    #     SELECT Y.root, Y.word 
    #     FROM (
    #         SELECT root, MAX(count) AS max_count FROM word_root GROUP BY root
    #     ) X 
    #     INNER JOIN word_root Y ON Y.root = X.root 
    #     AND Y.count = X.max_count GROUP BY Y.root
    # ) B ON B.root = A.root
    # JOIN winereviews_review C ON C.id = A.winereviews_review_id
    # WHERE winereviews_review_id IN
    #     (
    #         SELECT B.id
    #         FROM winereviews_review B
    #         JOIN 
    #         (
    #             SELECT A.id, AVG(rating) avg_rating
    #             FROM winereviews_wine A 
    #             JOIN winereviews_review B ON B.wine_id = A.id 
    #             GROUP BY A.id
    #             ORDER BY avg_rating DESC LIMIT 100
    #         ) A ON B.wine_id = A.id
    #     )
    # AND A.root NOT IN ('–','—','“','”','$','it','%%','(',')','10')
    # AND A.root NOT LIKE '20%%'
    # GROUP BY A.root
    # ORDER BY word_count DESC, word DESC
    # LIMIT %s;
    # '''
    
    with connection.cursor() as cursor:
        cursor.execute(sql, [number])
        words = cursor.fetchall()

    writer = csv.writer(response)
    writer.writerow(['id','value','avg_rating'])
    for w in words:
        writer.writerow([w[0], w[1], w[2]])
    return response 

def word_count_stats_rating_lo(request, number=200):
    response = HttpResponse(content_type='text/plain')

    sql = '''
    SELECT B.word, COUNT(winereviews_review_id) word_count, C.avg_rating
    FROM word_root_review A
    JOIN 
    (
        SELECT Y.root, Y.word 
        FROM (
            SELECT root, MAX(count) AS max_count FROM word_root GROUP BY root
        ) X 
        INNER JOIN word_root Y ON Y.root = X.root 
        AND Y.count = X.max_count GROUP BY Y.root
    ) B ON B.root = A.root
    JOIN word_root_sum C ON C.root = A.root
    WHERE winereviews_review_id IN
        (
            SELECT B.id
            FROM winereviews_review B
            JOIN 
            (
                SELECT A.id, AVG(rating) avg_rating
                FROM winereviews_wine A 
                JOIN winereviews_review B ON B.wine_id = A.id 
                GROUP BY A.id
                ORDER BY avg_rating ASC LIMIT 100
            ) A ON B.wine_id = A.id
        )
    AND A.root NOT IN ('–','—','“','”','$','it','%%','(',')','10')
    AND A.root NOT LIKE '20%%'
    GROUP BY A.root
    ORDER BY word_count DESC, word DESC
    LIMIT %s;
    '''
    
    with connection.cursor() as cursor:
        cursor.execute(sql, [number])
        words = cursor.fetchall()

    writer = csv.writer(response)
    writer.writerow(['id','value','avg_rating'])
    for w in words:
        writer.writerow([w[0], w[1], w[2]])
    return response
    
    
def word_count_stats_expensive(request, number=200):
    response = HttpResponse(content_type='text/plain')

    sql = '''
    SELECT B.word, COUNT(winereviews_review_id) word_count, AVG(D.price)
    FROM word_root_review A
    JOIN 
    (
        SELECT Y.root, Y.word 
        FROM (
            SELECT root, MAX(count) AS max_count FROM word_root GROUP BY root
        ) X 
        INNER JOIN word_root Y ON Y.root = X.root 
        AND Y.count = X.max_count GROUP BY Y.root
    ) B ON B.root = A.root
    JOIN winereviews_review C ON C.id = A.winereviews_review_id
    JOIN winereviews_wine D ON D.id = C.wine_id
    WHERE winereviews_review_id IN
        (
            SELECT B.id
            FROM winereviews_review B
            JOIN 
            (
                SELECT A.id
                FROM winereviews_wine A 
                ORDER BY price DESC LIMIT 100
            ) A ON B.wine_id = A.id
        )
    AND A.root NOT IN ('–','—','“','”','$','it','%%','(',')','10')
    AND A.root NOT LIKE '20%%'
    GROUP BY A.root
    ORDER BY word_count DESC, word DESC
    LIMIT %s;
    '''
    
    with connection.cursor() as cursor:
        cursor.execute(sql, [number])
        words = cursor.fetchall()

    writer = csv.writer(response)
    writer.writerow(['id','value','avg_price'])
    for w in words:
        writer.writerow([w[0], w[1], w[2]])
    return response 

    
def word_count_stats(request, number=200):
    response = HttpResponse(content_type='text/plain')

    sql = ''' 
        SELECT word, sum_count, avg_rating FROM word_root_sum WHERE skip = 0 LIMIT %s;
    '''
    with connection.cursor() as cursor:
        cursor.execute(sql, [number])
        words = cursor.fetchall()

    writer = csv.writer(response)
    writer.writerow(['id','value','rating'])
    for w in words:
        writer.writerow([w[0], w[1], w[2]])
    return response   




def consultancy(request):
    template = loader.get_template('winereviews/consultancy.html')
    context = {
        'a_var': 0,
    }
    return HttpResponse(template.render(context, request))



def variety_options(request):
    response = HttpResponse(content_type='text/csv')
    varieties = Variety.objects.all().order_by("name")
    writer = csv.writer(response)
    writer.writerow(['id','name'])
    for v in varieties:
        writer.writerow([v.id, v.name])
    return response



def variety_reviews(request, variety_id):
    response = HttpResponse(content_type='text/csv')
    sql = '''
        SELECT A.*
        FROM winereviews_review A
        JOIN winereviews_wine B ON A.wine_id = B.id
        JOIN winereviews_variety C ON B.variety_id = C.id
        AND C.id = %s
        LIMIT 100
    '''
    reviews = Review.objects.raw(sql, [variety_id])
    writer = csv.writer(response)
    writer.writerow(['country','description','designation','points','price','taster','variety','winery', 'id', 'likes','flag','vintage'])
    for r in reviews:
        writer.writerow([r.wine.winery.country, r.comment, r.wine.name, r.rating, r.wine.price, r.user.username, r.wine.variety.name, r.wine.winery.name, r.id, r.likes, r.flag, r.wine.vintage])
    return response

def review_create(request):
    if request.method == 'POST':
        form = WineReviewCreateForm(request.POST)
        with connection.cursor() as cursor:
            sql = '''
            INSERT INTO winereviews_review 
            (rating, comment, wine_id, user_id)
            VALUES (%s, %s, %s, %s)
            '''
            if request.POST['user_id'] == "":
                user_id = 21
            else:
                user_id = request.POST['user_id']
            cursor.execute(sql, [request.POST['rating'], request.POST['comment'], request.POST['wine_id'], user_id])
        return HttpResponseRedirect(reverse('reviews'))
    else:
        form = WineReviewCreateForm(initial={'user_id': request.user.id,})
        return render(request, 'winereviews/review_form.html', {'form': form})

    # path('review/<int:pk>/', views.review_update, name='review_update'),
    # path('review/<int:pk>/delete/', views.review_delete_actual, name='review_delete_actual'),

def review_delete_actual(request, pk):
    with connection.cursor() as cursor:
        sql = '''
            DELETE FROM winereviews_review 
            WHERE id = %s
        '''
        cursor.execute(sql, [pk])
        return HttpResponseRedirect(reverse('reviews'))

def review_update(request, pk):

isommelier/templates/winereviews/base.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="//d3js.org/d3.v4.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    {{ form.media.css }}
    <style>

      body {
          font-family: "Lato", sans-serif;
      }

      .sidenav {
          height: 100%;
          width: 160px;
          position: fixed;
          z-index: 1;
          top: 0;
          left: 0;
          background-color: #417690;
          overflow-x: hidden;
          padding-top: 20px;
      }

      .sidenav a {
          padding: 6px 8px 6px 16px;
          text-decoration: none;
          font-size: 20px;
          color: #f5dd5d;
          display: block;
      }

      .sidenav a:hover {
          color: #f1f1f1;
      }

      .main {
          margin-left: 160px; /* Same as the width of the sidenav */
          font-size: 15px; /* Increased text to enable scrolling */
          padding: 0px 10px;
      }

      @media screen and (max-height: 450px) {
          .sidenav {padding-top: 15px;}
          .sidenav a {font-size: 18px;}
      }
    </style>
  </head>

  <body>

    <div class="sidenav">
      <a href="{% url 'index' %}">Home</a>
      <a href="{% url 'consultancy' %}">Top Varietals</a>
      <a href="#side-bar-3">Ratings</a>
      <a href="#contact">Contact</a>
    </div>
    <div class="main">
      <div> <!-- Slide Show -->
        <section>
          <img class="mySlides" src="{% static "images/winery3.jpg" %}" style="max-height:100%;max-width:100%">
          <img class="mySlides" src="{% static "images/winery2.jpg" %}" style="max-height:100%;max-width:100%">
          <img class="mySlides" src="{% static "images/winery1.png" %}" style="max-height:100%;max-width:100%">
        </section>
      </div>
      
      
      {% block content %}
      {% endblock %}


    </div>
      
    <script>
      // Automatic Slideshow - change image every 3 seconds
      var myIndex = 0;
      carousel();
      function carousel() {
          var i;
          var x = document.getElementsByClassName("mySlides");
          for (i = 0; i < x.length; i++) {
             x[i].style.display = "none";
          }
          myIndex++;
          if (myIndex > x.length) {myIndex = 1}
          x[myIndex-1].style.display = "block";
          setTimeout(carousel, 3000);
      }

    </script>
    {{ form.media.js }}
        
  </body>
</html>

isommelier/templates/winereviews/consultancy.html
{% extends "winereviews/consultancybase.html" %}
{% load static %}
{% block custom_styles %}
g.node > circle {
    cursor: pointer;
}
{% endblock %}

{% block content %}

      <div id='side-bar-2'>
        <h2>Top Wines by Varietal</h2>

        <h4>Overview of our data assets</h4>
        <p style='font-style: italic;'>We have over 130,000 records in our database. Hover over each bubble to see the number of reviews we have for each wine variety.</p>
         <p style='font-style: italic;'>You can also choose a varietal and take a look at user reviews..</p>
          <!--Bubble Chart-->
        <div id='bubble1' style='margin:auto;width:60%'>
          <!--svg width="550" height="550" font-family="sans-serif" font-size="10" text-anchor="middle"></svg-->
          <script src="{% static "js/wine-variety-bubble.js" %}"></script>
        </div>


        <div style="text-align:center">
        <h4 style='margin-top:60px'>Click a wine variety Above</h4>
        <h4>Or select a  wine variety Below</h4>
          <form id="pickawine-form">
            <select id="pickawine-select">
              <option>Pick a wine</option>
            </select>
          </form>
        </div>
        <p>Results: </p>
        <div id='pickawine-result'></div>

      </div>

{% endblock %}

isommelier/templates/winereviews/consultancybase.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="//d3js.org/d3.v4.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <style>

      body {
          font-family: "Lato", sans-serif;
      }

      .sidenav {
          height: 100%;
          width: 160px;
          position: fixed;
          z-index: 1;
          top: 0;
          left: 0;
          background-color: #417690;
          overflow-x: hidden;
          padding-top: 20px;
      }

      .sidenav a {
          padding: 6px 8px 6px 16px;
          text-decoration: none;
          font-size: 20px;
          color: #f5dd5d;
          display: block;
      }

      .sidenav a:hover {
          color: #f1f1f1;
      }

      .main {
          margin-left: 160px; /* Same as the width of the sidenav */
          font-size: 15px; /* Increased text to enable scrolling */
          padding: 0px 10px;
      }

      @media screen and (max-height: 450px) {
          .sidenav {padding-top: 15px;}
          .sidenav a {font-size: 18px;}
      }
      .likebutton{
            cursor:pointer;
            border: none;
            height: -moz-available;
            width: -moz-available;
            }
       .map {
  height: 100%;
}

.water {
    fill: none;
}

.land {
  fill: #40403E;
  stroke: #31322D;
  stroke-width: 0.7px;
}


      {% block custom_styles %}{% endblock %}

    </style>

    {% block custom_head %}{% endblock %}

  </head>

  <body>

    <div class="sidenav">
      <a href="{% url 'index' %}">Home</a>
      <a href="{% url 'consultancy' %}">Top Varietals</a>
      <a href="{% url 'reviews' %}">Manage Reviews</a>
      <a href="{% url 'wine_list' %}">Manage Wines</a>
      <a href="{% url 'wine_review_search' %}">Wine Review Search</a>
      <a href="{% url 'worldmap-template' %}">Wines By Country</a>
    </div>
    <div class="main">
      <div> <!-- Slide Show -->
        <section>
        </section>
      </div>
      
      
      {% block content %}
      {% endblock %}


    </div>
      
    {% block scripts %}{% endblock %}
    
  </body>
</html>

isommelier/templates/winereviews/design_base.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="//d3js.org/d3.v4.js"></script>
    <style>

      body
      {
          font-family: "Lato", sans-serif;
          background-color: #efefef;
          margin:0;
      }
      div.main
      {
        width:1050px;
        margin: auto;
        padding-top: 50px;
      }
      /* Jquery UI Override */
      .ui-widget
      {
          font-family: "Lato", sans-serif;
      }

      {% block custom_styles %}{% endblock %}

    </style>
    
    {% block custom_styles_block %}{% endblock %}

    {% block custom_head %}{% endblock %}

  </head>

  <body>

      
    {% block header %}
    {% endblock %}

    <div class="main">
      <div> <!-- Slide Show -->
        <section>
        </section>
      </div>
      
      
      {% block content %}
      {% endblock %}


    </div>
      
    {% block scripts %}{% endblock %}
    
  </body>
</html>

isommelier/templates/winereviews/index.html
{% extends "winereviews/base.html" %}
{% load static %}
{% block content %}
      <div id='side-bar-1'>
        <h2>iSommelier</h2>
        <p>Looking for the perfect wine for your Friday night date? Well, iSommelier is the place to go to select the perfect pairing for your Foie Gras. Who needs the highbrow wine experts, when iSommelier is faster and less intimidating?</p> 
        <p>Many of the existing wine review websites are in a blog or forum format or require a subscription to browse the content, and we are looking to provide an interface that allows more intuitive and robust searching than what a blog/forum platform provides while being openly available the public.</p>
      
        <table id='icon' style="width:100%; margin-top:60px;">
          <tr style='text-align: center'>
            <td><img src="static/images/consultancy-icon.png" style="max-height:100%;max-width:100%"></td>
            <td><img src="{% static 'wine-icon.png' %}" style="max-height:100%;max-width:100%"></td>
          </tr>
          <tr style='text-align: center'>
            <td><h4>CONSULTANCY</h4></td>
            <td><h4>RATINGS</h4></td>
          </tr>
          <tr style='text-align: center'>
            <td style='width:50%'><div style='margin-left:20%;margin-right:20%'>The iSommelier is the perfect platform for wine enthusiasts to read about and discover new wines without the pressure of consulting with experts.</div>
            </td>
            <td style='width:50%'><div style='margin-left:20%;margin-right:20%'>The iSommelier also provides a platform for the public to share their own experiences and reviews and keep track of their favorites</div>
            </td>
          </tr>          
        </table>
      </div> 
{% endblock %}

isommelier/templates/winereviews/review.html
{% extends "winereviews/base.html" %}
{% load static %}
{% block content %}

      <div id='side-bar-2'>

        <h2>Wine Review</h2>

      </div>

{% endblock %}

isommelier/templates/winereviews/review_form.html
{% extends "winereviews/consultancybase.html" %}
{% load static %}
{% block content %}

      <div id='side-bar-2'>

        <h2>Wine Review</h2>
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            
            <div class="ui-widget">
              <label for="wines">wines: </label>
              <input id="wines">
            </div>  
            
            <input type="submit" value="Save" />
        </form>
      </div>

{% endblock %}


{% block scripts %}

    {{ block.super }}

    <script>
    
      $(function() {
        $("#wines").autocomplete({
          source: "{% url 'wine_type_ahead' %}",
          select: function (event, ui) { //item selected
            AutoCompleteSelectHandler(event, ui)
          },
          minLength: 3,
        });
      });
    
      function AutoCompleteSelectHandler(event, ui)
      {
        $("#id_wine_id").val(ui.item.id);
      }
    
    </script>

{% endblock %}

isommelier/templates/winereviews/wine_detail.html
{% extends "winereviews/consultancybase.html" %}
{% load static %}
{% block content %}

      <div id='side-bar-2'>

        <h2>Wine</h2>
        
        <p><strong>variety: </strong><br />
        {{ wine.variety }}</p>

        <p><strong>winery: </strong><br />
        {{ wine.winery }}</p>

        <p><strong>description: </strong><br />
        {{ wine.description }}</p>

        <p><strong>name: </strong><br />
        {{ wine.name }}</p>

        <p><strong>price: </strong><br />
        {{ wine.price }}</p>
        
        <p><strong>created at: </strong><br />
        {{ wine.created_at }}</p>
        
        <a href="/winereviews/wine/{{ wine.id }}/review">Review this wine</a>

      </div>

{% endblock %}